mode: 'development'

http:
  host: 'localhost'
  port: 5001

db:
  application:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    database: 'recognition-service'
    user: 'postgres'
    password: 'root'
    schema: 'public'
  
  lexema8: 
    type: 'postgres'
    host: 'localhost'
    port: 5432
    database: 'recognition-service'
    user: 'postgres'
    password: 'root'
    schema: 'public'

yandex:
  OAuth: "y0_AgAAAABnJ6UeAATuwQAAAAD2Mtb9EqmSg7CCSjGx70gNB43BCMX__UM"
  XFolderId: "b1go1rnknjf12uq4bn22"